services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/api
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "source /src/.venv/bin/activate && poetry run alembic upgrade head && poetry run uvicorn src.api:app --log-level info --host 0.0.0.0 --port 80"

  db:
    image: postgres:16.3-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      PGUSER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_DRIVER: ${DB_DRIVER}

volumes:
  pg_data:
