apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-project-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-project
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
