apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-phase-1-api
  labels:
    app: tech-challenge-phase-1-api
spec:
  selector:
    matchLabels:
      app: tech-challenge-phase-1-api
  template:
    metadata:
      labels:
        app: tech-challenge-phase-1-api
    spec:
      containers:
      - name: tech-challenge-phase-1-api
        image: 717145188069.dkr.ecr.us-east-1.amazonaws.com/project-01:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: DB_HOST
          value: meu-cluster-aurora.cluster-cq38yxucn72w.us-east-1.rds.amazonaws.com
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: tech_challenge_dev
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_DRIVER
          value: postgresql
        command: ["bash", "-c", "poetry run alembic upgrade head && poetry run uvicorn src.api:app --log-level info --host 0.0.0.0 --port 80"]

