apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-phase-1-api
  labels:
    app: tech-challenge-phase-1-api
spec:
  selector:
    matchLabels:
      app: tech-challenge-phase-1-api
  template:
    metadata:
      labels:
        app: tech-challenge-phase-1-api
    spec:
      initContainers:
        - name: init-migrate
          image: $(IMAGE_NAME)
          imagePullPolicy: IfNotPresent
          command: ["poetry", "run", "alembic", "upgrade", "head"]
          env:
            - name: DATABASE_HOST
              value: postgres-service
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: myappdb
            - name: DATABASE_USER
              value: myappuser
            - name: DATABASE_PASSWORD
              value: mypassword
            - name: ALEMBIC_CONFIG
              value: /app/alembic.ini
            - name: IMAGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: image-config
                  key: IMAGE_NAME
          volumeMounts:
          - name: config-volume
            mountPath: /app
      containers:
        - name: tech-challenge-phase-1-api
          image: $(IMAGE_NAME)
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
      volumes:
      - name: config-volume
        configMap:
          name: image-config