apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tech-challenge-phase-1-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tech-challenge-phase-1-api
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
