"""Add product table.

Revision ID: a1242ea8396e
Revises: 648bcbec70ef
Create Date: 2024-05-25 20:38:21.810024

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1242ea8396e"
down_revision: Union[str, None] = "648bcbec70ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:  # noqa: D103
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("images", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_uuid"), "products", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:  # noqa: D103
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_uuid"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
