"""Add orders table.

Revision ID: 1148fe37860d
Revises: a1242ea8396e
Create Date: 2024-05-26 14:46:37.794845

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1148fe37860d"
down_revision: Union[str, None] = "a1242ea8396e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:  # noqa: D103
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "CONFIRMED",
                "IN_PREPARATION",
                "READY_FOR_DELIVERY",
                "PAID",
                "DELIVERED",
                "CANCELED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_method", sa.Enum("MERCADO_PAGO", "CASH", name="paymentmethod"), nullable=False
        ),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_uuid"), "orders", ["uuid"], unique=True)
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"]),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_items_product_id"), "order_items", ["product_id"], unique=False)
    op.create_index(op.f("ix_order_items_uuid"), "order_items", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:  # noqa: D103
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_items_uuid"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_product_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_orders_uuid"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
