name: Database Migrations

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  REGION_DEFAULT: "us-east-1"

jobs:
  migrate:
    name: Migrate
    runs-on: ubuntu-latest
    environment: production
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout application repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          alembic upgrade head
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}